services:
  web:
    build: .
    container_name: rocketon-website
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
    expose:
      - "80"
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rocketon-website.rule=Host(`rocketon.xyz`) || Host(`www.rocketon.xyz`)"
      - "traefik.http.routers.rocketon-website.entrypoints=websecure"
      - "traefik.http.routers.rocketon-website.tls=true"
      - "traefik.http.services.rocketon-website.loadbalancer.server.port=80"

networks:
  traefik-proxy:
    external: true
